# Generated by Django 6.0.1 on 2026-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='problem_type',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend')], default='backend', max_length=20),
        ),
    ]
