# Generated by Django 6.0.1 on 2026-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_codingproblem_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
