# Generated by Django 6.0.1 on 2026-03-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_codingproblem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java'), ('html', 'HTML'), ('css', 'CSS')], default='python', max_length=20),
        ),
    ]
